### ISSUE TITLE
Suggestion: Make it ReallyFree

### ISSUE THREAD

**Issue by kentfredric** [zostay/CPAN-Sidekick#22]
The first time I saw it on Play, I basically dismissed it because it had a fee associated, and didn't look any further.

Mostly, because the CPAN spirit is very much not "pay to play".

Even though you say "If you would like to participate in the project or wish to avoid the small fee to install " .... I didn't initially even get that far, all I saw was basically: 
![screenshot - 120514 - 05 31 00](https://cloud.githubusercontent.com/assets/44790/5301731/f2d6dd98-7c3f-11e4-8bef-1541cd345c62.png)

And that was enough deterrent.

And many people who are just wanting to learn/do perl are likely _not_ to have the tools at thier disposal to build an APK, and that serves as further detterrent. ( Myself, I have the tools at my disposal, but your project is eclipse based, and I haven't worked out how I'm supposed to build it when I don't have eclipse and don't know eclipse, as I've only really just gotten started on this using the IntelliJ system )

However, seeing its claiming to ferry 100% of funds to Perl Org., and given so far it hasn't been hugley profitable, I consider it may be of more benefit to the perl community to be Free without obligation to pay first.

I was considering DIYing something but I don't really know what I'm doing in androidspace yet, and I was considering a model as follows:
1. A truely free free version with no ads or any such nagware as the default version
2. A second version **with** ads for those who want to support Perl.org in some tiny way but aren't in the position to do so directly, and are happy to observe advertising to make this happen.
3. A third version, or "donorware" that is essentially the same as version 1, except with  a shiney badge you can show off to let people know you donate or something like that.

In short, trying to make "being a financial pay off for Perl" should be a secondary concern, not a primary IMHO.

Serving as a quality tool for navigating CPAN should be a primary objective. 

Some of my rationale is also intended to avoid deterring security concious people, for instance: 
- Having no ads in the vanilla edition means their installer won't prompt them for permissions that they won't feel they need ( and this concern is why I didn't merely suggest it being a toggle )
- Avoiding that "in App purchases" thing and having the permissions not warn about "Could cost you money" is in my books, a "Good Thing", and should avoid deterring users for fears of hidden costs.

And partially, we need to have some sort of incentive to not inspire people to **need** to create competition. If this app is decent, we're prematurely deterrring people with the forced donation, and competition like [this](https://play.google.com/store/apps/details?id=org.notlocalhost.cpan) will arise and be divisive.

I mean to get stuck in and make a bunch of other suggestions, but I don't fully grok android dev yet, and contributing in this way at this time is far superior to starting my own crappy competition. :)

**Comment by Getty** [comment]
+1

**Comment by karenetheridge** [comment]
+1

**Comment by Freso** [comment]
I found this through F-Droid and there was no fee there. I would not have looked at this twice if I had seen it in the Google Play store with a purchase fee.

**Comment by zostay** [comment]
I pulled it from the Play store sometime ago.
