### ISSUE TITLE
Search dialog duplicated on Ice Cream Sandwich

### ISSUE THREAD

**Issue by clintongormley** [zostay/CPAN-Sidekick#9]
Hiya Zostay

Great app! I've been wanting something like this.  Bit buggy though:

This is with v 0.3 from the market.  On my Nexus S with Ice Cream Sandwich, I get two search boxes at the top of the screen: one with a grey background containing the text "CPAN Module Search" and one with a white bg (which receives focus) and has the magnifying glass button to the right of it.

The box with the grey background works, as long as I press the 'Go' button on the keyboard. The magnifying glass button doesn't work.

If I press the magnifying glass button on my phone (as opposed to the magnifying glass button in your UI) then focus switches between the two search boxes. But if I use that button to move focus to the top search box, then 'Go' doesn't work. I have to actually tap on the search box to focus, then type, then press Go.

hope this helps

**Comment by zostay** [comment]
Thanks for reporting this. I did not test on ICS, but I know exactly what's happening. It should be an easy fix. I just need to hide the search box for ICS phones and let it use the search added to the ActionBar for tablet support.

Hopefully my Incredible 2 will be upgraded to ICS in the next couple months and testing ICS will get easier.

**Comment by zostay** [comment]
Fixed in 30086c79d883e3f3e4539f53b839baece766d3ea

I will to release 0.3.1 with this fix shortly.

**Comment by clintongormley** [comment]
works great++
